version: '3.3'

services:
  postgres:
    image: mongo:3.5
    restart: always
    environment:
       - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
       - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
  redis:
    image: redis:7.0.4-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --loglevel warning
volumes:
  redis:
    driver: local
