name: Build and push Docker images 🚀

on:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
      docker-token: ${{ steps.login.outputs.docker_token }}
    steps:
      - name: Login to Docker Hub
        id: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            webserver: webserver
            frontend: frontend
            caching: caching
            transaction-server: transaction-server
            database: database

  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJSON(needs.changes.outputs.packages) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.image }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/day-trading-${{ matrix.image }}:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ needs.changes.outputs.docker-token }}
